### ISSUE TITLE
Undefined variable: pwHint

### ISSUE THREAD

**Issue by ettolo** [sjaakp/yii2-pluto#16]
First of all, THANK YOU!
I installed pluto in Yii2 advanced template.
After first registration, i login as admin, then click on "settings" and get "Undefined variable: pwHint" error.
Can you help me?
Best regards,
Nicola

**Comment by paskuale75** [comment]
[Look here ;) ](https://github.com/paskuale75/yii2-pluto/commit/4e384306412b4c9c9fa3c3f022090a0605c5564c)

**Comment by ettolo** [comment]
Thank you Paskuale!
Shoudn't this be corrected in this repository?

**Comment by sjaakp** [comment]
Yes, of course!

Actually, it was pulled in already, but I forgot to create a new release. I just corrected that.

 

Sorry, thanks,

Sjaak

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: ettolo <notifications@github.com> 
Verzonden: zaterdag 1 februari 2020 14:27
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: Re: [sjaakp/yii2-pluto] Undefined variable: pwHint (#16)

 

Thank you Paskuale!
Shoudn't this be corrected in this repository?

**Comment by ettolo** [comment]
Thank you Paskuale75 and Sjaaak.
Unfortunately still doesn't work for me... The Paskuale mod was already in my code
I updated pluto (Updating sjaakp/yii2-pluto (1.0.8 => 1.0.9)) but the error is still there clicking on 'settings' menu item (/pluto/settings):
```
Undefined variable: pwHint

1. in /home/mydomain/vendor/sjaakp/yii2-pluto/views/default/_password.phpat line 25
16171819202122232425262728293031323334/* @var $this yii\web\View */
/* @var $model sjaakp\pluto\models\User */
/* @var $form yii\widgets\ActiveForm */
/* @var $options array */
/* @var $pwHint string */
 
if (in_array('reveal', $model->flags)): ?>
    <?= $form->field($model, 'password')
    ->widget(Password::class, ['options' => $options ?? []])
    ->hint($pwHint)
    ?>
    <?php if (in_array('double', $model->flags)): ?>
        <?= $form->field($model, 'password_repeat')->widget(Password::class) ?>
    <?php endif;
else: ?>
    <?= $form->field($model, 'password')
    ->passwordInput($options ?? [])
    ->hint($pwHint)
    ?>

```

I think that the mod Paskuale75 suggested for login.php view should be applied also to all other views with password (delete.php, download.php, recover.php, settings.php) because they all give the same error

**Comment by sjaakp** [comment]
You’re right again!

Just created another new release.

 

Thanks

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: ettolo <notifications@github.com> 
Verzonden: maandag 3 februari 2020 10:15
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Sjaak Priester <sjaak@sjaakpriester.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [sjaakp/yii2-pluto] Undefined variable: pwHint (#16)

 

Thank you Paskuale75 and Sjaaak.
Unfortunately still doesn't work for me... The Paskuale mod was already in my code
I updated pluto (Updating sjaakp/yii2-pluto (1.0.8 => 1.0.9)) but the error is still there clicking on 'settings' menu item (/pluto/settings):

`1. in /home/mydomain/vendor/sjaakp/yii2-pluto/views/default/_password.phpat line 25
16171819202122232425262728293031323334/* @var <https://github.com/var>  $this yii\web\View /
/ @var <https://github.com/var>  $model sjaakp\pluto\models\User /
/ @var <https://github.com/var>  $form yii\widgets\ActiveForm /
/ @var <https://github.com/var>  $options array /
/ @var <https://github.com/var>  $pwHint string */

if (in_array('reveal', $model->flags)): ?>
field($model, 'password') ->widget(Password::class, ['options' => $options ?? []]) ->hint($pwHint) ?>
flags)): ?>
field($model, 'password_repeat')->widget(Password::class) ?>

field($model, 'password') ->passwordInput($options ?? []) ->hint($pwHint) ?>`

**Comment by ettolo** [comment]
Thank you,
Updated and working!

**Comment by paskuale75** [comment]
in download and in deleteMe actions there was still this problem, i just fatt push to fix it.
