### ISSUE TITLE
Get the following error when I try to install your yii2-pluto extension with composer

### ISSUE THREAD

**Issue by lloyd966** [sjaakp/yii2-pluto#32]
I get the following error when I try to install your yii2-pluto extension with composer

[InvalidArgumentException]
Package sjaakp/yii2-pluto has a requirement incompatable with your PHP version, PHP extensions and Composer version

I am running the latest version of Yii2 (ie: 2.0.40 (December 23, 2020) using the Yii2 Basic Template on Windows 10 using Wampserver 3.2.3 with
PHP 7.3.21 and MYSQL 8.0.21.

Any suggestions on how I can get this install with Composer would be greatly appreciated.

Thanking you in advance for your kind cooperation, I look forward to your response.

Regards,

Lloyd

**Comment by lloyd966** [comment]
Can someone please help me out.  I really need to get this installed and working

Thank you

**Comment by sjaakp** [comment]
Pluto by mistake required an older version of yii2-swiftmailer. I corrected this in a new version 1.0.12. Hope this also solves your issue.

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl

 

Van: lloyd966 <notifications@github.com> 
Verzonden: maandag 8 februari 2021 17:14
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Subscribed <subscribed@noreply.github.com>
Onderwerp: [sjaakp/yii2-pluto] Get the following error when I try to install your yii2-pluto extension with composer (#32)

 

I get the following error when I try to install your yii2-pluto extension with composer

[InvalidArgumentException]
Package sjaakp/yii2-pluto has a requirement incompatable with your PHP version, PHP extensions and Composer version

I am running the latest version of Yii2 (ie: 2.0.40 (December 23, 2020) using the Yii2 Basic Template on Windows 10 using Wampserver 3.2.3 with
PHP 7.3.21 and MYSQL 8.0.21.

Any suggestions on how I can get this install with Composer would be greatly appreciated.

Thanking you in advance for your kind cooperation, I look forward to your response.

Regards,

Lloyd

**Comment by lloyd966** [comment]
Unfortunately I am still getting the same error with composer. If you could get this to work, I would really appreciate it.

Otherwise I will try to manually install the the extension.  I realize that I need to unpack the zip file and place the contents in the correct directory. I am not sure if the directory should be  

vendor/sjaakp/yii2-pluto/      or     vendor/sjaakp/pluto/ 

Please confirm which is the correct directory path.

Thank you

Lloyd

**Comment by lloyd966** [comment]
Any update on my problem

Thank you

Lloyd

**Comment by lloyd966** [comment]
Sorry to bother you again, but I really need your help to get this extension installed and running. Can you please reply to my questions concerning installing your extension with composer, and what directory should I should be installing the extension, if I 
go ahead and install it manually.

Thank you, I really appreciate any help you can give me.

Lloyd

**Comment by sjaakp** [comment]
I feel with you, but until now I’m not able to reproduce your problem, sorry. Still looking.

 

As to your question: it doesn’t matter where you put the files, but you’ll have to make sure that PHP knows where to find them. Frankly, I’m afraid it won’t solve your issues.

 

  _____  

Sjaak Priester

sjaak@sjaakpriester.nl <mailto:sjaak@sjaakpriester.nl> 

 

Van: lloyd966 <notifications@github.com> 
Verzonden: zondag 14 februari 2021 15:31
Aan: sjaakp/yii2-pluto <yii2-pluto@noreply.github.com>
CC: Sjaak Priester <sjaak@sjaakpriester.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [sjaakp/yii2-pluto] Get the following error when I try to install your yii2-pluto extension with composer (#32)

 

Sorry to bother you again, but I really need your help to get this extension installed and running. Can you please reply to my questions concerning installing your extension with composer, and what directory should I should be installing the extension, if I
go ahead and install it manually.

Thank you, I really appreciate any help you can give me.

Lloyd

**Comment by lloyd966** [comment]
I was able to install with composer using the following command:

composer require sjaakp/yii2-pluto --ignore-platform-reqs

I followed the readme instructions and made the changes to my the config files.

After running migrate, I ran Yii Pluto, but get an error as follows:

PHP Parse Error 'yii\base\ErrorException' with message 'syntax error, unexpected ';''
in D:\wamp64\www\yii2-app-basic\vendor\sjaakp\yii2-pluto\Module.php:174

Any Ideas?

Lloyd

**Comment by rossaddison** [comment]
I experienced a similar error ';' a while ago unfortunately did not document it. Pluto was not the error. Sorry I cannot help. One of those annoying errors. I seem to recall it being a php error. I can confirm that Pluto is running fine on php 7.4.9. I know Yii2 had an issue with 7.4.1.

**Comment by rossaddison** [comment]
Have you managed to resolve your issue? My window cleaning app rossaddison\yii2-h2h-core is running fine on:
php 7.4.9
mysql  5.7.31
yii2-advanced template derived.
